language: cpp
compiler:
  - gcc
before_script:
 - sudo apt-get update
 - sudo apt-get install git-buildpackage pbuilder debian-archive-keyring
 - sudo pbuilder create --distribution sid  --mirror ftp://ftp.nl.debian.org/debian/ --debootstrapopts "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg"
script:
 - DIST=sid BUILDER=pbuilder git-buildpackage --git-pbuilder
 - false
